from __future__ import annotations

from app.intelligence_sources.contracts import IntelligenceSourceDefinition
from app.neural_bus.types import NeuralEventType
from app.shared_awareness.types import AwarenessDomain


PROVIDER_CATALOG: tuple[IntelligenceSourceDefinition, ...] = (
    IntelligenceSourceDefinition(
        source_id="news_rss_public",
        source_type="NEWS",
        provider_name="RSS Feeds",
        provider_category="public_news",
        optional_env_vars=("NEWS_RSS_FEEDS",),
        setup_url_or_notes="No key required. Configure comma-separated RSS URLs in NEWS_RSS_FEEDS when operator selects feeds.",
        cost_model="free",
        priority=10,
        enabled_by_default=True,
        neural_event_type=NeuralEventType.NEWS_DETECTED.value,
        awareness_domain=AwarenessDomain.NEWS.value,
        target_tables=("news_sources", "news_raw_events", "news_normalized_events", "news_impact_scores"),
        metadata={"connector_state": "existing_rss_collector", "production_collection": "disabled_until_configured"},
    ),
    IntelligenceSourceDefinition(
        source_id="gdelt_public",
        source_type="NEWS",
        provider_name="GDELT",
        provider_category="public_news",
        setup_url_or_notes="No key required for public GDELT APIs. Connector skeleton only in this phase.",
        cost_model="free",
        priority=20,
        enabled_by_default=False,
        neural_event_type=NeuralEventType.NEWS_DETECTED.value,
        awareness_domain=AwarenessDomain.NEWS.value,
        target_tables=("news_sources", "news_raw_events", "news_normalized_events"),
        metadata={"connector_state": "planned_contract"},
    ),
    IntelligenceSourceDefinition(
        source_id="newsapi",
        source_type="NEWS",
        provider_name="NewsAPI",
        provider_category="news_api",
        required_env_vars=("NEWS_API_KEY",),
        setup_url_or_notes="Get an API key from https://newsapi.org/ and place it in NEWS_API_KEY.",
        cost_model="free_tier_or_paid",
        priority=30,
        neural_event_type=NeuralEventType.NEWS_DETECTED.value,
        awareness_domain=AwarenessDomain.NEWS.value,
        target_tables=("news_sources", "news_raw_events", "news_normalized_events", "news_impact_scores"),
        metadata={"connector_state": "planned_contract"},
    ),
    IntelligenceSourceDefinition(
        source_id="cryptopanic",
        source_type="NEWS",
        provider_name="CryptoPanic",
        provider_category="crypto_news",
        required_env_vars=("CRYPTOPANIC_API_KEY",),
        setup_url_or_notes="Get an API token from https://cryptopanic.com/developers/api/ and place it in CRYPTOPANIC_API_KEY.",
        cost_model="free_tier_or_paid",
        priority=40,
        neural_event_type=NeuralEventType.NEWS_DETECTED.value,
        awareness_domain=AwarenessDomain.NEWS.value,
        target_tables=("news_sources", "news_raw_events", "news_normalized_events", "news_impact_scores"),
        metadata={"connector_state": "planned_contract"},
    ),
    IntelligenceSourceDefinition(
        source_id="news_sports_politics_rss",
        source_type="NEWS",
        provider_name="Sports/Politics RSS Sources",
        provider_category="topic_news",
        optional_env_vars=("NEWS_RSS_FEEDS",),
        setup_url_or_notes="Use public RSS feeds for sports, politics, regulation, and breaking news; no dedicated key required.",
        cost_model="free",
        priority=50,
        neural_event_type=NeuralEventType.NEWS_DETECTED.value,
        awareness_domain=AwarenessDomain.NEWS.value,
        target_tables=("news_sources", "news_raw_events", "news_normalized_events"),
        metadata={"connector_state": "existing_rss_collector"},
    ),
    IntelligenceSourceDefinition(
        source_id="polymarket_gamma_public",
        source_type="WHALE",
        provider_name="Polymarket Gamma",
        provider_category="polymarket_public",
        setup_url_or_notes="No key required. Existing runtime already checks Gamma read-only source health.",
        cost_model="free",
        priority=10,
        enabled_by_default=True,
        neural_event_type=NeuralEventType.WHALE_DETECTED.value,
        awareness_domain=AwarenessDomain.WHALE.value,
        target_tables=("whale_sources", "whale_events", "whale_market_scores"),
        metadata={"connector_state": "existing_public_source_status"},
    ),
    IntelligenceSourceDefinition(
        source_id="polymarket_clob_public_trades",
        source_type="WHALE",
        provider_name="Polymarket CLOB/Data API Trades",
        provider_category="polymarket_public",
        setup_url_or_notes="No key required for read-only trade/activity checks. Scanner contract is prepared; no trading auth used.",
        cost_model="free",
        priority=20,
        enabled_by_default=True,
        neural_event_type=NeuralEventType.WHALE_DETECTED.value,
        awareness_domain=AwarenessDomain.WHALE.value,
        target_tables=("whale_sources", "whale_events", "whale_registry", "whale_profiles"),
        metadata={"connector_state": "scanner_skeleton_exists"},
    ),
    IntelligenceSourceDefinition(
        source_id="polymarket_clob_authenticated_readonly",
        source_type="WHALE",
        provider_name="Polymarket CLOB Authenticated Read-Only",
        provider_category="polymarket_authenticated",
        required_env_vars=("POLYMARKET_CLOB_API_KEY", "POLYMARKET_CLOB_SECRET", "POLYMARKET_CLOB_PASSPHRASE"),
        optional_env_vars=("POLYMARKET_CLOB_HOST",),
        setup_url_or_notes="Use for authenticated account/orderbook metadata only after operator supplies credentials. This phase never sends orders.",
        cost_model="free_account",
        priority=30,
        neural_event_type=NeuralEventType.WHALE_DETECTED.value,
        awareness_domain=AwarenessDomain.WHALE.value,
        target_tables=("whale_sources", "whale_events", "source_status"),
        metadata={"connector_state": "planned_readonly_contract", "trading_allowed": False},
    ),
    IntelligenceSourceDefinition(
        source_id="whale_profile_builder_internal",
        source_type="WHALE",
        provider_name="Internal Whale Profile Builder",
        provider_category="internal_derived",
        setup_url_or_notes="No external key. Builds profiles from source-backed whale/trade events.",
        cost_model="internal",
        priority=40,
        enabled_by_default=True,
        neural_event_type=NeuralEventType.WHALE_DETECTED.value,
        awareness_domain=AwarenessDomain.WHALE.value,
        target_tables=("whale_registry", "whale_profiles", "whale_follow_decisions"),
        metadata={"connector_state": "existing_derived_neuron"},
    ),
    IntelligenceSourceDefinition(
        source_id="x_twitter_api",
        source_type="SOCIAL",
        provider_name="X/Twitter API",
        provider_category="social_api",
        required_env_vars=("X_BEARER_TOKEN",),
        setup_url_or_notes="Create an X developer app and place the bearer token in X_BEARER_TOKEN.",
        cost_model="paid_or_limited_free",
        priority=10,
        neural_event_type=NeuralEventType.SOCIAL_SPIKE.value,
        awareness_domain=AwarenessDomain.SOCIAL.value,
        target_tables=("social_sources", "social_raw_events", "social_hype_scores", "social_noise_scores"),
        metadata={"connector_state": "planned_contract"},
    ),
    IntelligenceSourceDefinition(
        source_id="reddit_api",
        source_type="SOCIAL",
        provider_name="Reddit API",
        provider_category="social_api",
        required_env_vars=("REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET"),
        optional_env_vars=("REDDIT_USER_AGENT",),
        setup_url_or_notes="Create a Reddit application and place credentials in REDDIT_CLIENT_ID and REDDIT_CLIENT_SECRET. Set REDDIT_USER_AGENT for production API etiquette.",
        cost_model="free_account",
        priority=20,
        neural_event_type=NeuralEventType.SOCIAL_SPIKE.value,
        awareness_domain=AwarenessDomain.SOCIAL.value,
        target_tables=("social_sources", "social_raw_events", "social_hype_scores", "social_narratives"),
        metadata={"connector_state": "collector_stub_exists"},
    ),
    IntelligenceSourceDefinition(
        source_id="telegram_public_channels",
        source_type="SOCIAL",
        provider_name="Telegram Public Channels",
        provider_category="social_channel",
        required_env_vars=("TELEGRAM_API_ID", "TELEGRAM_API_HASH"),
        optional_env_vars=("TELEGRAM_BOT_TOKEN", "TELEGRAM_CHANNELS"),
        setup_url_or_notes="Create a Telegram API app at https://my.telegram.org/ and place API ID/hash in the env vars. Configure TELEGRAM_CHANNELS before ingestion.",
        cost_model="free_account",
        priority=30,
        neural_event_type=NeuralEventType.SOCIAL_SPIKE.value,
        awareness_domain=AwarenessDomain.SOCIAL.value,
        target_tables=("social_sources", "social_raw_events", "social_hype_scores"),
        metadata={"connector_state": "planned_contract", "requires_operator_channel_allowlist": True},
    ),
    IntelligenceSourceDefinition(
        source_id="discord_optional",
        source_type="SOCIAL",
        provider_name="Discord Optional",
        provider_category="social_channel",
        optional_env_vars=("DISCORD_BOT_TOKEN", "DISCORD_CHANNELS"),
        setup_url_or_notes="Disabled by default. Only enable with explicit server/channel allowlist and operator approval.",
        cost_model="free_account",
        priority=50,
        enabled_by_default=False,
        neural_event_type=NeuralEventType.SOCIAL_SPIKE.value,
        awareness_domain=AwarenessDomain.SOCIAL.value,
        target_tables=("social_sources", "social_raw_events"),
        metadata={"connector_state": "optional_disabled", "enabled_requires_operator_approval": True},
    ),
    IntelligenceSourceDefinition(
        source_id="manual_social_ingestion",
        source_type="SOCIAL",
        provider_name="Manual Social Ingestion",
        provider_category="manual",
        setup_url_or_notes="No key. Existing manual social processing can ingest operator-supplied source-backed rows.",
        cost_model="internal",
        priority=60,
        neural_event_type=NeuralEventType.SOCIAL_SPIKE.value,
        awareness_domain=AwarenessDomain.SOCIAL.value,
        target_tables=("social_sources", "social_raw_events"),
        metadata={"connector_state": "existing_manual_ingestion"},
    ),
    IntelligenceSourceDefinition(
        source_id="ollama_local",
        source_type="AI_CONTEXT",
        provider_name="Ollama Local",
        provider_category="local_ai",
        optional_env_vars=("OLLAMA_BASE_URL", "OLLAMA_MODEL_FAST", "OLLAMA_MODEL_PRIMARY", "OLLAMA_MODEL_REASONING"),
        setup_url_or_notes="Install Ollama locally and set OLLAMA_BASE_URL. Local model names remain optional until selected.",
        cost_model="local_compute",
        priority=10,
        enabled_by_default=True,
        neural_event_type=NeuralEventType.AI_CONTEXT_UPDATED.value,
        awareness_domain=AwarenessDomain.CANDIDATE.value,
        target_tables=("ai_requests", "ai_cache_entries", "ai_budget_ledger"),
        metadata={"connector_state": "local_ai_worker_exists"},
    ),
    IntelligenceSourceDefinition(
        source_id="openai_api",
        source_type="AI_CONTEXT",
        provider_name="OpenAI API",
        provider_category="cloud_ai",
        required_env_vars=("OPENAI_API_KEY",),
        setup_url_or_notes="Optional cloud escalation provider. Place key in OPENAI_API_KEY after budget policy is configured.",
        cost_model="paid_usage",
        priority=30,
        neural_event_type=NeuralEventType.AI_CONTEXT_UPDATED.value,
        awareness_domain=AwarenessDomain.CANDIDATE.value,
        target_tables=("ai_requests", "ai_escalations", "ai_budget_ledger"),
        metadata={"connector_state": "planned_optional_cloud", "budget_governor_required": True},
    ),
    IntelligenceSourceDefinition(
        source_id="anthropic_api",
        source_type="AI_CONTEXT",
        provider_name="Anthropic API",
        provider_category="cloud_ai",
        required_env_vars=("ANTHROPIC_API_KEY",),
        setup_url_or_notes="Optional cloud escalation provider. Place key in ANTHROPIC_API_KEY after budget policy is configured.",
        cost_model="paid_usage",
        priority=40,
        neural_event_type=NeuralEventType.AI_CONTEXT_UPDATED.value,
        awareness_domain=AwarenessDomain.CANDIDATE.value,
        target_tables=("ai_requests", "ai_escalations", "ai_budget_ledger"),
        metadata={"connector_state": "cloud_worker_skeleton_exists", "budget_governor_required": True},
    ),
    IntelligenceSourceDefinition(
        source_id="ai_budget_cache_internal",
        source_type="AI_CONTEXT",
        provider_name="AI Budget Governor + Cache",
        provider_category="internal_policy",
        setup_url_or_notes="No key. Existing AI budget/cache compatibility surface.",
        cost_model="internal",
        priority=20,
        enabled_by_default=True,
        neural_event_type=NeuralEventType.AI_CONTEXT_UPDATED.value,
        awareness_domain=AwarenessDomain.CANDIDATE.value,
        target_tables=("ai_budget_ledger", "ai_cache_entries"),
        metadata={"connector_state": "existing_policy_layer"},
    ),
    IntelligenceSourceDefinition(
        source_id="market_memory_outcomes",
        source_type="MARKET_MEMORY",
        provider_name="Market/Trade/No-Trade Outcomes",
        provider_category="internal_memory",
        setup_url_or_notes="No external key. Consumes event, trade, no-trade, source reliability, whale reliability, and AI usefulness outcomes.",
        cost_model="internal",
        priority=10,
        enabled_by_default=True,
        neural_event_type=NeuralEventType.MEMORY_UPDATED.value,
        awareness_domain=AwarenessDomain.MEMORY.value,
        target_tables=("market_memory_v2", "source_reliability_memory", "whale_memory", "no_trade_memory"),
        metadata={"connector_state": "existing_memory_builders"},
    ),
    IntelligenceSourceDefinition(
        source_id="mock_intelligence_provider",
        source_type="MARKET_MEMORY",
        provider_name="Mock/Test Provider",
        provider_category="test_provider",
        setup_url_or_notes="Test-only provider contract. It reports readiness and never produces production intelligence.",
        cost_model="test_only",
        priority=999,
        enabled_by_default=False,
        neural_event_type=NeuralEventType.MEMORY_UPDATED.value,
        awareness_domain=AwarenessDomain.MEMORY.value,
        target_tables=("intelligence_connector_tests",),
        metadata={"connector_state": "test_only", "production_intelligence": False},
    ),
)


def catalog_by_id() -> dict[str, IntelligenceSourceDefinition]:
    return {source.source_id: source for source in PROVIDER_CATALOG}
