from __future__ import annotations

from enum import StrEnum


class PositionReactionType(StrEnum):
    ADVERSE_NEWS = "ADVERSE_NEWS"
    POSITIVE_NEWS = "POSITIVE_NEWS"
    WHALE_ENTRY = "WHALE_ENTRY"
    WHALE_EXIT = "WHALE_EXIT"
    LIQUIDITY_DROP = "LIQUIDITY_DROP"
    LIQUIDITY_IMPROVED = "LIQUIDITY_IMPROVED"
    SPREAD_WIDENED = "SPREAD_WIDENED"
    SPREAD_IMPROVED = "SPREAD_IMPROVED"
    RISK_INCREASED = "RISK_INCREASED"
    RISK_DECREASED = "RISK_DECREASED"
    EXIT_DEGRADED = "EXIT_DEGRADED"
    EXIT_IMPROVED = "EXIT_IMPROVED"
    PNL_RISING = "PNL_RISING"
    PNL_FALLING = "PNL_FALLING"
    CAPITAL_PRESSURE = "CAPITAL_PRESSURE"
    POSITION_AGING = "POSITION_AGING"
    POSITION_ORDERBOOK_REFRESHED = "POSITION_ORDERBOOK_REFRESHED"
    POSITION_EXIT_RISK = "POSITION_EXIT_RISK"
    TOKEN_BOOK_UNAVAILABLE_FOR_OPEN_POSITION = "TOKEN_BOOK_UNAVAILABLE_FOR_OPEN_POSITION"
    EXIT_REVIEW = "EXIT_REVIEW"
    HOLD_REVIEW = "HOLD_REVIEW"
    MISSING_POSITION_TOKEN = "MISSING_POSITION_TOKEN"
    TOKEN_IDENTITY_DRIFT_REVIEW = "TOKEN_IDENTITY_DRIFT_REVIEW"
    NO_REACTION = "NO_REACTION"
