from __future__ import annotations

from enum import StrEnum


class MeshFinalStance(StrEnum):
    STRONG_SUPPORT = "STRONG_SUPPORT"
    SUPPORT = "SUPPORT"
    WATCH = "WATCH"
    NO_TRADE = "NO_TRADE"
    BLOCK = "BLOCK"
    EXIT_WATCH = "EXIT_WATCH"
    EXIT_RECOMMENDED = "EXIT_RECOMMENDED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class MeshFinalAction(StrEnum):
    OBSERVE = "OBSERVE"
    WATCH = "WATCH"
    NO_TRADE = "NO_TRADE"
    BLOCK = "BLOCK"
    PAPER_CANDIDATE_REVIEW = "PAPER_CANDIDATE_REVIEW"
    EXIT_REVIEW = "EXIT_REVIEW"
    HOLD_REVIEW = "HOLD_REVIEW"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class MeshSafetyStatus(StrEnum):
    SAFE_NON_EXECUTING = "SAFE_NON_EXECUTING"
    BLOCKED_NON_EXECUTING = "BLOCKED_NON_EXECUTING"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    ERROR = "ERROR"


PROTECTIVE_BRAINS = {"RISK_BRAIN", "CAPITAL_BRAIN", "EXIT_BRAIN"}
