CREATE TABLE IF NOT EXISTS ai_mesh_insights (
    id BIGSERIAL PRIMARY KEY,
    ai_mesh_insight_id TEXT NOT NULL UNIQUE,
    run_id TEXT,
    insight_type TEXT NOT NULL,
    market_id TEXT,
    condition_id TEXT,
    side TEXT,
    token_id TEXT,
    source_event_id TEXT,
    multi_trigger_id TEXT,
    proactive_candidate_seed_id TEXT,
    seed_mesh_inquiry_id TEXT,
    opportunity_score_id TEXT,
    model_provider TEXT NOT NULL DEFAULT 'NONE',
    model_name TEXT,
    prompt_version TEXT NOT NULL,
    summary TEXT,
    reasoning_brief TEXT,
    entities_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    topics_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    related_markets_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    direction_hint TEXT NOT NULL DEFAULT 'UNKNOWN',
    direction_confidence NUMERIC NOT NULL DEFAULT 0,
    thesis_type TEXT NOT NULL DEFAULT 'UNKNOWN',
    thesis_confidence NUMERIC NOT NULL DEFAULT 0,
    expected_hold_time_seconds INTEGER,
    exit_target TEXT,
    time_stop_seconds INTEGER,
    invalidation_condition TEXT,
    already_priced_in_state TEXT NOT NULL DEFAULT 'NOT_EVALUATED',
    missing_evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    supporting_evidence_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    contradicting_evidence_ids_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    confidence NUMERIC NOT NULL DEFAULT 0,
    risk_notes_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    why_not_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    recommended_mesh_action TEXT NOT NULL DEFAULT 'NO_ACTION',
    is_execution_authority BOOLEAN NOT NULL DEFAULT FALSE,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_mesh_insights_market_side ON ai_mesh_insights (market_id, side);
CREATE INDEX IF NOT EXISTS idx_ai_mesh_insights_seed ON ai_mesh_insights (proactive_candidate_seed_id);
CREATE INDEX IF NOT EXISTS idx_ai_mesh_insights_type ON ai_mesh_insights (insight_type, created_at DESC);

CREATE TABLE IF NOT EXISTS ai_mesh_intelligence_runs (
    id BIGSERIAL PRIMARY KEY,
    run_id TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    insights_created INTEGER NOT NULL DEFAULT 0,
    calls_attempted INTEGER NOT NULL DEFAULT 0,
    calls_succeeded INTEGER NOT NULL DEFAULT 0,
    calls_failed INTEGER NOT NULL DEFAULT 0,
    avg_latency_ms INTEGER NOT NULL DEFAULT 0,
    local_model_status_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    latest_error TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
